name: Build for Linux
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Get Godot
        run: |
          wget -O godot.zip https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.4-stable_linux.x86_64
          
      - name: Install patchelf
        run: sudo apt-get update && sudo apt-get install -y patchelf


      - name: Get Export Templates
        run: |
          wget -O templates.tpz https://github.com/godotengine/godot-builds/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.stable
          unzip templates.tpz -d ~/.local/share/godot/export_templates/4.4.stable
          mv ~/.local/share/godot/export_templates/4.4.stable/templates/* ~/.local/share/godot/export_templates/4.4.stable/
          rmdir ~/.local/share/godot/export_templates/4.4.stable/templates

      - name: Export project (Linux)
        run: |
          mkdir builds
          cd flumi
          ../godot/Godot_v4.4-stable_linux.x86_64 --headless --export-release "Linux" ../builds/Flumi.x86_64
      - name: Verify binary exists
        run: |
          if [ ! -f builds/Flumi.x86_64 ]; then
            echo "we failed"
            exit 1
          fi
          echo "exported! we can move on"
      - name: Set up directory structure
        run: |
          cd flumi-pkg
          mkdir -p usr/{bin, lib/flumi}
          cp ../builds/*.so ./usr/lib/flumi
          cp ../builds/Flumi.x86_64 ./usr/bin
          patchelf --set-rpath '$ORIGIN/../lib/flumi' Flumi.x86_64
      - name: Build package
        run: |
          dpkg-deb -b flumi-pkg
      - name: Upload deb
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: ./flumi-pkg.deb
      
